version: "3.8"
services:
  nifi:
    build:
      context: .
      dockerfile: nifi.dockerfile
    networks:
      spark_network:
        aliases:
          - nifi
    ports:
      - "8080:8080"
    depends_on:
      - nifi_registry
  nifi_registry:
    build:
      context: .
      dockerfile: nifi_registry.dockerfile
    networks:
      spark_network:
        aliases:
          - nifi_registry
    volumes:
      - ./data/nifi_registry/database:/usr/nifi-registry-0.7.0/database
      - ./data/nifi_registry/flow_storage:/usr/nifi-registry-0.7.0/flow_storage
      - ./data/nifi_registry/extension_bundles:/usr/nifi-registry-0.7.0/extension_bundles
    ports:
      - "18080:18080"
  kafka:
    build:
      context: .
      dockerfile: kafka.dockerfile
    networks:
      spark_network:
        aliases:
          - kafka
  spark:
    build:
      context: .
      dockerfile: spark.dockerfile
    networks:
      spark_network:
        aliases:
          - spark
networks:
  spark_network:
